# db/seeds.rb

Therapist.create(name: 'John Doe, LPC', insurance: 'UnitedHealth Group', remote: true, location: 'Brooklyn')
Therapist.create(name: 'Jane Smith, LCSW', insurance: 'Anthem', remote: false, location: 'Manhattan')
Therapist.create(name: 'David Johnson, LMFT', insurance: 'Kaiser Permanente', remote: true, location: 'Queens')
Therapist.create(name: 'Emily White, PhD', insurance: 'Ambetter', remote: false, location: 'Bronx')
Therapist.create(name: 'Michael Brown, LCADC', insurance: 'Humana', remote: true, location: 'Staten Island')
Therapist.create(name: 'Olivia Davis, PsyD', insurance: 'Blue Cross Blue Shield', remote: false, location: 'Brooklyn')
Therapist.create(name: 'William Miller, CADC', insurance: 'Cigna', remote: true, location: 'Manhattan')
Therapist.create(name: 'Sophia Wilson, MA', insurance: 'Aetna', remote: false, location: 'Queens')
Therapist.create(name: 'Daniel Taylor, LCSW-C', insurance: 'UnitedHealth Group', remote: true, location: 'Bronx')
Therapist.create(name: 'Ava Anderson, LMHC', insurance: 'Anthem', remote: false, location: 'Staten Island')
Therapist.create(name: 'Ethan Doe, MSW', insurance: 'Kaiser Permanente', remote: true, location: 'Brooklyn')
Therapist.create(name: 'Samantha Smith, CAC', insurance: 'Ambetter', remote: false, location: 'Manhattan')
Therapist.create(name: 'Richard Johnson, EdD', insurance: 'Humana', remote: true, location: 'Queens')
Therapist.create(name: 'Grace White, APRN', insurance: 'Blue Cross Blue Shield', remote: false, location: 'Bronx')
Therapist.create(name: 'Alexander Brown, CCMHC', insurance: 'Cigna', remote: true, location: 'Staten Island')
Therapist.create(name: 'Emma Davis, LCMFT', insurance: 'Aetna', remote: false, location: 'Brooklyn')
Therapist.create(name: 'Henry Miller, CEDS', insurance: 'UnitedHealth Group', remote: true, location: 'Manhattan')
Therapist.create(name: 'Isabella Wilson, RPT', insurance: 'Anthem', remote: false, location: 'Queens')
Therapist.create(name: 'Noah Taylor, LCSW', insurance: 'Kaiser Permanente', remote: true, location: 'Bronx')
Therapist.create(name: 'Mia Anderson, LPCC', insurance: 'Ambetter', remote: false, location: 'Staten Island')
Therapist.create(name: 'Lucas Scott, LMFT', insurance: 'CVS Health (Aetna)', remote: true, location: 'Brooklyn')
Therapist.create(name: 'Chloe Johnson, LCSW', insurance: 'Molina Healthcare', remote: false, location: 'Manhattan')
Therapist.create(name: 'Elijah Martin, PhD', insurance: 'GuideWell (Florida Blue)', remote: true, location: 'Queens')
Therapist.create(name: 'Lily Thomas, PsyD', insurance: 'HCSC (Health Care Service Corporation)', remote: false, location: 'Bronx')
Therapist.create(name: 'Gabriel Hernandez, LPC', insurance: 'Highmark', remote: true, location: 'Staten Island')


