name: Rails CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.2' # Set up Ruby 3.1.2

    - name: Install dependencies
      run: |
        gem install rails -v 7.0.8
        bundle install

    - name: Migrate and Seed DB
      run: |
        rails db:migrate
        rails db:migrate RAILS_ENV=test
        rails db:seed

    - name: Run tests
      run: rails test test/controllers/therapists_controller_test.rb

    - name: Precompile assets
      run: rails assets:precompile

    - name: Deploy to mytherapistdirectory.com
      env:
        DO_SSH_KEY: ${{ secrets.DO_SSH_KEY }} # Digital Ocean SSH key stored in GitHub secrets
        SERVER_USER: root
        SERVER_IP: 159.203.128.202
      run: |
        echo "$DO_SSH_KEY" > deploy_key
        chmod 600 deploy_key
        ssh -i deploy_key -o "StrictHostKeyChecking=no" $SERVER_USER@$SERVER_IP << 'ENDSSH'
          cd /root/ROR-Therapists-Project/therapist_directory
          git pull
          bundle install
          rails db:migrate
          rails db:migrate RAILS_ENV=test
          rails db:seed
          rails assets:precompile
          if lsof -t -i:80; then
            timeout 60 kill $(lsof -t -i:80)
          fi
          timeout 60 nohup rails server -b 0.0.0.0 -p 80 > log.txt 2>&1 &
          exit
        ENDSSH
      
